### ISSUE TITLE
Finalize design

### ISSUE THREAD

**Issue by uellenberg** [nsccs/club_website#22]
Figure out what the site design will be. What colors will we use? Will we follow NSC, or do our own styling?

**Comment by ShlokChaitanya** [comment]
The NSC design is kind of outdated and old fashioned. We should opt for a newer and more modern design for this.

**Comment by uellenberg** [comment]
> The NSC design is kind of outdated and old fashioned. We should opt for a newer and more modern design for this.

Yeah, this is one thing we've been discussing. We're using the NSC design right now because it's what we have, but we'll probably switch to something different later.
