### ISSUE TITLE
Add resources page

### ISSUE THREAD

**Issue by uellenberg** [nsccs/club_website#28]
Add the resources page and redesign it.

**Comment by jaredscarr** [comment]
What is this supposed to be? Can I help with this one?

**Comment by uellenberg** [comment]
> What is this supposed to be? Can I help with this one?

@jaredscarr Honestly, I'm not totally sure. It was on the original design of the club website.
![image](https://github.com/nsccs/club_website/assets/66662148/9dd4bcf8-08b7-4dbf-b958-179d1538b559)
This is fine web-development-wise but I'm not sure what content was planned to go here. We can flesh it out, or just remove it.

**Comment by jaredscarr** [comment]
I like the idea, but it might mean maintaining a bunch of links that could change. The get involved section is covered by Discord. Coursework is covered by the individual teachers and curriculum should probably be outside the scope of the club. Honestly, I think it would be fine to remove this and let these types of questions be directed to Discord where discussion can occur. What do you think?
